/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trlabs_trscanner_jni_ImageBlur */

#ifndef _Included_trlabs_trscanner_jni_ImageBlur
#define _Included_trlabs_trscanner_jni_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trlabs_trscanner_jni_ImageBlur
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_trlabs_trscanner_jni_ImageBlur_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     trlabs_trscanner_jni_ImageBlur
 * Method:    blurBitMap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_trlabs_trscanner_jni_ImageBlur_blurBitMap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
